// Generated Localization File

import Foundation

enum AbstractionsStrings {
  enum TransactionModelLocalization {
    static let stateSentTitle = NSLocalizedString("State.Sent.Title", bundle: .module, comment: "")
    static let stateReceivedTitle = NSLocalizedString("State.Received.Title", bundle: .module, comment: "")
    static let stateDeclinedTitle = NSLocalizedString("State.Declined.Title", bundle: .module, comment: "")
    static let stateCancelledTitle = NSLocalizedString("State.Cancelled.Title", bundle: .module, comment: "")
    static let stateNotSentTitle = NSLocalizedString("State.NotSent.Title", bundle: .module, comment: "")
  }
  enum CurrencyModelLocalization {
    static let usdName = NSLocalizedString("USD.Name", bundle: .module, comment: "")
    static let usdUnit = NSLocalizedString("USD.Unit", bundle: .module, comment: "")
    static let eurName = NSLocalizedString("EUR.Name", bundle: .module, comment: "")
    static let eurUnit = NSLocalizedString("EUR.Unit", bundle: .module, comment: "")
    static let rubName = NSLocalizedString("RUB.Name", bundle: .module, comment: "")
    static let rubUnit = NSLocalizedString("RUB.Unit", bundle: .module, comment: "")
    static let idrName = NSLocalizedString("IDR.Name", bundle: .module, comment: "")
    static let idrUnit = NSLocalizedString("IDR.Unit", bundle: .module, comment: "")
    static let uahName = NSLocalizedString("UAH.Name", bundle: .module, comment: "")
    static let uahUnit = NSLocalizedString("UAH.Unit", bundle: .module, comment: "")
    static let uzsName = NSLocalizedString("UZS.Name", bundle: .module, comment: "")
    static let uzsUnit = NSLocalizedString("UZS.Unit", bundle: .module, comment: "")
    static let inrName = NSLocalizedString("INR.Name", bundle: .module, comment: "")
    static let inrUnit = NSLocalizedString("INR.Unit", bundle: .module, comment: "")
    static let gbpName = NSLocalizedString("GBP.Name", bundle: .module, comment: "")
    static let gbpUnit = NSLocalizedString("GBP.Unit", bundle: .module, comment: "")
    static let aedName = NSLocalizedString("AED.Name", bundle: .module, comment: "")
    static let aedUnit = NSLocalizedString("AED.Unit", bundle: .module, comment: "")
    static let cnyName = NSLocalizedString("CNY.Name", bundle: .module, comment: "")
    static let cnyUnit = NSLocalizedString("CNY.Unit", bundle: .module, comment: "")
    static let bynName = NSLocalizedString("BYN.Name", bundle: .module, comment: "")
    static let bynUnit = NSLocalizedString("BYN.Unit", bundle: .module, comment: "")
    static let brlName = NSLocalizedString("BRL.Name", bundle: .module, comment: "")
    static let brlUnit = NSLocalizedString("BRL.Unit", bundle: .module, comment: "")
    static let tryName = NSLocalizedString("TRY.Name", bundle: .module, comment: "")
    static let tryUnit = NSLocalizedString("TRY.Unit", bundle: .module, comment: "")
    static let kztName = NSLocalizedString("KZT.Name", bundle: .module, comment: "")
    static let kztUnit = NSLocalizedString("KZT.Unit", bundle: .module, comment: "")
    static let ngnName = NSLocalizedString("NGN.Name", bundle: .module, comment: "")
    static let ngnUnit = NSLocalizedString("NGN.Unit", bundle: .module, comment: "")
    static let krwName = NSLocalizedString("KRW.Name", bundle: .module, comment: "")
    static let krwUnit = NSLocalizedString("KRW.Unit", bundle: .module, comment: "")
    static let thbName = NSLocalizedString("THB.Name", bundle: .module, comment: "")
    static let thbUnit = NSLocalizedString("THB.Unit", bundle: .module, comment: "")
    static let bdtName = NSLocalizedString("BDT.Name", bundle: .module, comment: "")
    static let bdtUnit = NSLocalizedString("BDT.Unit", bundle: .module, comment: "")
    static let chfName = NSLocalizedString("CHF.Name", bundle: .module, comment: "")
    static let chfUnit = NSLocalizedString("CHF.Unit", bundle: .module, comment: "")
    static let jpyName = NSLocalizedString("JPY.Name", bundle: .module, comment: "")
    static let jpyUnit = NSLocalizedString("JPY.Unit", bundle: .module, comment: "")
    static let cadName = NSLocalizedString("CAD.Name", bundle: .module, comment: "")
    static let cadUnit = NSLocalizedString("CAD.Unit", bundle: .module, comment: "")
    static let ilsName = NSLocalizedString("ILS.Name", bundle: .module, comment: "")
    static let ilsUnit = NSLocalizedString("ILS.Unit", bundle: .module, comment: "")
    static let gelName = NSLocalizedString("GEL.Name", bundle: .module, comment: "")
    static let gelUnit = NSLocalizedString("GEL.Unit", bundle: .module, comment: "")
    static let vndName = NSLocalizedString("VND.Name", bundle: .module, comment: "")
    static let vndUnit = NSLocalizedString("VND.Unit", bundle: .module, comment: "")
  }
}
