//
//  Workspace.swift
//  oChatManifests
//
//  Created by Vitalii Sosin on 05.03.2024.
//

import ProjectDescription

let workspace = Workspace(
  name: "oChat",
  projects: ["./**"],
  generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
